# Generated by Django 5.2.9 on 2025-12-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('contact', 'Contact'), ('feedback', 'Feedback')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(max_length=4000)),
                ('page_url', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('captcha_provider', models.CharField(default='turnstile', max_length=32)),
                ('captcha_verified', models.BooleanField(default=False)),
                ('captcha_error_codes', models.JSONField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_handled', models.BooleanField(default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', '-created_at'], name='submissions_ip_addr_80688c_idx'), models.Index(fields=['email', 'content_hash', '-created_at'], name='submissions_email_2e4b42_idx')],
            },
        ),
    ]
